# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='PENDING', max_length=10)),
                ('task', models.CharField(db_index=True, max_length=256)),
                ('task_id', models.UUIDField(db_index=True, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('args', models.TextField(blank=True)),
                ('kwargs', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('timestamp_prerun', models.DateTimeField(blank=True, editable=False, null=True)),
                ('timestamp_postrun', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
